[package]
name = "complgen"
version = "0.1.0"
edition = "2021"
description = "A programming-language-agnostic shell completions generator"

[dependencies]
nom = "7.1.3"
proptest = "1.1.0"
roaring = "0.10.1"
thiserror = "1.0.39"
