[package]
name = "complgen"
version = "0.1.0"
edition = "2021"
description = "A programming-language-agnostic shell completions generator"

[profile.profiling]
inherits = "release"
debug = true

[dependencies]
itertools = "0.10.5"
nom = "7.1.3"
roaring = "0.10.1"
rustc-hash = "1.1.0"
thiserror = "1.0.39"

[dev-dependencies]
proptest = "1.1.0"
